esphome:
  name: ${device_name}
  friendly_name: ${device_name_friendly}

logger:
  level: INFO

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/New_York

switch:
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: Restart in Safe-Mode